license = 'MIT'
mods = [{modId = 'nucleus_codec', version = '1.1.4', displayName = 'Nucleus (Codec)', description = 'Various utilities for interaction with data, serialization, and deserialization', authors = 'RedPxnda', logoFile = 'icon.png'}]
dependencies.nucleus_codec = [{modId = 'neoforge', mandatory = true, versionRange = '[21.0.0-beta,)', ordering = 'NONE', side = 'BOTH'}, {modId = 'minecraft', mandatory = true, versionRange = '[${minecraft_version},)', ordering = 'NONE', side = 'BOTH'}, {modId = 'architectury', mandatory = true, versionRange = '[${architectury_version},)', ordering = 'NONE', side = 'BOTH'}]
mixins = []
modLoader = 'javafml'
loaderVersion = '[1,)'
