license = 'MIT'
mods = [{modId = 'nucleus_expression', version = '2.0.0', displayName = 'Nucleus (Expression)', description = 'A way to execute code, perform calculations, etc. in data', authors = 'RedPxnda'}]
dependencies.nucleus_expression = [{modId = 'neoforge', mandatory = true, versionRange = '[21.0.0-beta,)', ordering = 'NONE', side = 'BOTH'}, {modId = 'minecraft', mandatory = true, versionRange = '[${minecraft_version},)', ordering = 'NONE', side = 'BOTH'}, {modId = 'architectury', mandatory = true, versionRange = '[${architectury_version},)', ordering = 'NONE', side = 'BOTH'}]
mixins = []
modLoader = 'javafml'
loaderVersion = '[1,)'
