modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "nucleus"
version = "${version}"
displayName = "Nucleus"
authors = "RedPxnda"
description = '''
A simple library mod focused on making development easier.
'''
#logoFile = ""

[[dependencies.nucleus]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nucleus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nucleus]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"