license = 'MIT'
mods = [{modId = 'nucleus_pose', version = '2.0.0', displayName = 'Nucleus (Pose)', description = 'Adds a simple player animation system', authors = 'RedPxnda'}]
dependencies.nucleus_pose = [{modId = 'neoforge', mandatory = true, versionRange = '[21.0.0-beta,)', ordering = 'NONE', side = 'BOTH'}, {modId = 'minecraft', mandatory = true, versionRange = '[${minecraft_version},)', ordering = 'NONE', side = 'BOTH'}, {modId = 'architectury', mandatory = true, versionRange = '[${architectury_version},)', ordering = 'NONE', side = 'BOTH'}]
mixins = []
modLoader = 'javafml'
loaderVersion = '[1,)'
