license = 'MIT'
mods = [{modId = 'nucleus_trinket', version = '1.0.1', displayName = 'Nucleus (Trinket)', description = 'Multiplatform Trinkets/Curios API abstraction', authors = 'RedPxnda'}]
dependencies.nucleus_trinket = [{modId = 'forge', mandatory = true, versionRange = '[47,)', ordering = 'NONE', side = 'BOTH'}, {modId = 'minecraft', mandatory = true, versionRange = '[${minecraft_version},)', ordering = 'NONE', side = 'BOTH'}, {modId = 'architectury', mandatory = true, versionRange = '[${architectury_version},)', ordering = 'NONE', side = 'BOTH'}]
modLoader = 'javafml'
loaderVersion = '[47,)'
