license = 'MIT'
mods = [{modId = 'nucleus', version = '2.1.2', displayName = 'Nucleus (Core)', description = 'A library mod focused on making multi-platform mod development easier.', authors = 'RedPxnda', logoFile = 'icon.png'}]
dependencies.nucleus = [{modId = 'neoforge', mandatory = true, versionRange = '[21.0.0-beta,)', ordering = 'NONE', side = 'BOTH'}, {modId = 'minecraft', mandatory = true, versionRange = '[${minecraft_version},)', ordering = 'NONE', side = 'BOTH'}, {modId = 'architectury', mandatory = true, versionRange = '[${architectury_version},)', ordering = 'NONE', side = 'BOTH'}]
mixins = [{config = 'nucleus-core.mixins.json'}, {config = 'nucleus-core-common.mixins.json'}]
modLoader = 'javafml'
loaderVersion = '[1,)'
