license = 'MIT'
mods = [{modId = 'nucleus_registration', version = '1.0.2', displayName = 'Nucleus (Registration)', description = 'Yet another cross-platform registration library.', authors = 'RedPxnda'}]
dependencies.nucleus_registration = [{modId = 'neoforge', mandatory = true, versionRange = '[21.0.0-beta,)', ordering = 'NONE', side = 'BOTH'}, {modId = 'minecraft', mandatory = true, versionRange = '[${minecraft_version},)', ordering = 'NONE', side = 'BOTH'}, {modId = 'architectury', mandatory = true, versionRange = '[${architectury_version},)', ordering = 'NONE', side = 'BOTH'}]
mixins = []
modLoader = 'javafml'
loaderVersion = '[1,)'
