name: Create Github Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Read Gradle Properties
        uses: BrycensRanch/read-properties-action@v1
        id: properties
        with:
          file: gradle.properties
          all: true

      - name: Read changelog.md
        id: changelog
        uses: jaywcjlove/github-action-read-file@v1
        with:
          path: changelog.md

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}
          release_name: Nucleus Release v${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.content }}

      - name: Upload Fabric Jar to Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ steps.all.outputs.mod_version }}/nucleus-fabric-${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}.jar
          tag: v${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}
          overwrite: true

      - name: Upload Forge Jar to Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ steps.all.outputs.mod_version }}/nucleus-forge-${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}.jar
          tag: v${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}
          overwrite: true

      - name: Upload Common Jar to Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ steps.all.outputs.mod_version }}/nucleus-common-${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}.jar
          tag: v${{ steps.all.outputs.minecraft_version }}+${{ steps.all.outputs.mod_version }}
          overwrite: true
      
